namespace CCompiler {
  public enum MiddleOperator {/*Block, If, IfElse, Switch, Case, Default, Break,
                              Continue, While, Do, For, Label,*/ Goto,
                              AssignRegister, /*SaveFromRegister,*/ Compare,
                              ClearRegisters, InspectFlagByte, InspectRegister,
                              JumpRegister, Interrupt, Expression, Declaration,
                              PushZero, PushOne, PushFloat, PopFloat, TopFloat,
                              PopEmpty, Comma, Assign, LogicalOr, AssignInitSize,
                              LogicalAnd, BitwiseIOr, BitwiseXOr, BitwiseAnd,
                              Equal, EqualZero, NotEqual, SignedLessThan,
                              SignedLessThanEqual, SignedGreaterThan,
                              SignedGreaterThanEqual, UnsignedLessThan,
                              UnsignedLessThanEqual, UnsignedGreaterThan,
                              UnsignedGreaterThanEqual, ShiftLeft,
                              ShiftRight, BinaryAdd, BinarySubtract,
                              SignedMultiply, SignedDivide, SignedModulo,
                              UnsignedMultiply, UnsignedDivide, UnsignedModulo,
                              UnaryAdd, UnarySubtract, DecreaseStack, ParameterInitSize,
                              LogicalNot, BitwiseNot, address, Deref, Call, PostCall, // PreCall, PostCallIntegral, PostCallFloating,
                              Parameter, Empty, Return, Increment, Decrement, /*Exit,*/ CallHeader,
                              FunctionStart, FunctionEnd, //LoadStatusByte,
                              Conditional, SetReturnValue, GetReturnValue, Case, CaseEnd,
                              IntegralToIntegral, IntegralToFloating, FloatingToIntegral,
                              ArrayToPointer, FunctionToPointer, StringToPointer,
                              ValueOffset, AddressOffset, CheckTrackMapFloatStack,
                              Index, Dot, Arrow, Variable, Value, Carry, NotCarry,
                              SystemInit, SystemParameter, SystemCall};
}